# Site
title:             Partici.PE 
bio:                'Grupo responsável pelo projeto: SOM NA RURAL'
description:        "Grupo responsável pelo projeto: SOM NA RURAL"
locale:             en_US
baseurl: "/somnarural" # the subpath of your site, e.g. /blog
url: "https://abduzidos.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname: participe-1

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Recife, PE
email:              ccmr@cesar.school, cfp@cesar.school, gmb@cesar.school, mvmwec@cesar.school, osmn@cesar.school, taal@cesar.school, yasc@cesar.school 

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
